name: CI/CD Pipeline for AR2EN Translation Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s tests

  # Step 2: Build and Push Docker Image
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ar2en_translation_service:latest
            ${{ secrets.DOCKER_USERNAME }}/ar2en_translation_service:${{ github.sha }}

  # Step 3: Deploy the Application
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Server
        env:
          DEPLOYMENT_API_KEY: ${{ secrets.DEPLOYMENT_API_KEY }}
        run: |
          curl -X POST https://your-deployment-api.com/deploy \
            -H "Authorization: Bearer $DEPLOYMENT_API_KEY" \
            -d '{"image": "your-dockerhub-username/ar2en_translation_service:latest"}'
